[NF] add client
Go-Java-Go/yandex-geocode-client pull request #1
Opened 2021-05-07 10:03 UTC by almaznur91

2021-05-07 17:20 UTC, senyast4745 requested changes
Мне кажется, что по сути мы можем к тому же вынести каркас всех клиентов в отдельную библиотеку, но это не точно

2021-05-07 17:20 UTC, senyast4745 commented on client_city.go
> +		endpoint:            "",
А это прям на / запрос?

2021-05-07 17:20 UTC, senyast4745 commented on client_city.go
> +		apiName:             "",
Тут по задумке надо "GeoCode". Это по сути имя клиента который ты вызываешь
Если тут например появятся ещё другие клиенты, то так их будет удобно различать

2021-05-07 17:20 UTC, senyast4745 commented on models.go
> +	enUS Lang = "en_RU" /* enUS response in English, Russian map features;*/
тут скорее всего en_Us

2021-05-07 17:20 UTC, senyast4745 commented on models.go
> +type Tit struct {
Не уверен, что все поля нужны. Мн кажется на большинство можно было бы забить

2021-05-11 10:15 UTC, almaznur91 commented on models.go
> +type Tit struct {
хотел полностью поддержать апи)

2021-05-11 10:15 UTC, almaznur91 commented on models.go
> +	enUS Lang = "en_RU" /* enUS response in English, Russian map features;*/
да, ты прав, поправлю

2021-05-11 10:15 UTC, mazanur commented on client_city.go
> +		endpoint:            "",
ага

2021-05-11 10:16 UTC, almaznur91 commented on client_city.go
> +		apiName:             "",
понял

2021-05-11 10:41 UTC, senyasdt commented on models.go
> +type Tit struct {
Просто усложняет понимание, того что происходит

2021-05-25 06:09 UTC, almaznur91 commented
@senyast4745 посмотри плиз, солью, чтобы выпустить тег

2021-05-25 09:13 UTC, senyast4745 commented on models.go
> +	XML  ResponseFormat = "xml"
И такое случается в этой жизни?)

2021-05-25 09:13 UTC, senyast4745 approved these changes
@almaznur91 все ок)

2021-05-26 06:46 UTC, almaznur91 commented on models.go
> +	XML  ResponseFormat = "xml"
что я могу сделать?) 
блин, почему мне пушки не приходят гитхаб приложения )

2021-05-26 06:46 UTC, merged